#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
  #    username: sdc
#    password: 123456@sdc
#    url: jdbc:mysql://58.119.112.10:11030/sdcdevelop?characterEncoding=utf-8&useSSL=false
#  jpa:
#    show-sql: true
#  jackson:
#    default-property-inclusion: non_null   #全局设定返回不为空的值
spring:
  data:
    elasticsearch:
      cluster-name: chen
      cluster-nodes: 127.0.0.1:9300
  profiles:
    active: production
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dblogin
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update #create每次运行建立一个新的表，如果存在数据会删除原有表；update 如果有数据会继续保留
    show-sql: true #在控制台显示sql语句，方便调试
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
#  servlet-path: /sell

#logging:
#  pattern:
#    console: "%d - %msg%n"
#  level: info

wechat:
  mpAppId: wx7e585d995f58d7d6
  mpAppSecret: 311a4e1283aea428d20eb644615b53aa