spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: sdc
    password: 123456@sdc
    url: jdbc:mysql://58.119.112.10:11030/studevelope?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#  jackson:
#    default-property-inclusion: non_null   #全局设定返回不为空的值
#server:
#  servlet-path: /sell

#logging:
#  pattern:
#    console: "%d - %msg%n"
#  level: info

wechat:
  mpAppId: wx0b6356c5690adc27
  mpAppSecret: 9d09164246aeb4bbae46ec50d7afc6d4
server:
  port: 8086

projectUrl:
  weChatMpAuthorize: http://zhiheyikaoqin.cn
  weChatOpenAuthorize: http://zhiheyikaoqin.cn
  sdc: http://zhiheyikaoqin.cn
  homeAddress: /home.html

