server:
  port: 8086
  servlet-path: /sdc

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: bigdata
    password: 123456
    url: jdbc:mysql://58.119.112.10:3306/studevelope?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  jackson:
#    default-property-inclusion: non_null   #全局设定返回不为空的值

#logging:
#  pattern:
#    console: "%d - %msg%n"
#  level: info

wechat:
  mpAppId: wx0b6356c5690adc27
  mpAppSecret: 9d09164246aeb4bbae46ec50d7afc6d4

projectUrl:
  weChatMpAuthorize: http://zhiheyikaoqin.cn
  weChatOpenAuthorize: http://zhiheyikaoqin.cn
  sdc: http://zhiheyikaoqin.cn
  homeAddress: /user/home

#projectUrl:
#  weChatMpAuthorize: http://zhongkeruitong.top/sdc
#  weChatOpenAuthorize: http://zhongkeruitong.top/sdc
#  sdc: http://zhongkeruitong.top/sdc
#  homeAddress: /user/home
logging:
  config: classpath:logback-spring.xml
  level: trace
